
C:\Users\User\work\gits\jextra\legacy\bofor_2005>assloa
  UNDEF : @,@                                                                    
 ASSLOA END
 ---  1-ALONG : IN STATE 1 POSIT 1 NOT FOUND                                            
 ---  2-HAPPEN: CANNOT ALLOCATE STRING, STRHIB=2, FSYM=2                                
 ---  3-EMITT : SYMBOL 3 IN STATE 3 NOT FOUND                                           
 ---  4-PARSE : TEST-TRACE STATE=4, ITEM=4                                              
 ---  5-SETALL: TOO MUCH SET-ELEMENTS, FSET=5, SETHIB=5                                 
 ---  6-PREDEL: STATE 6 IS NOT A PREDECESSOR OF STATE 6                                 
 ---  7-HAMAP : CANNOT ALLOCATE SYMBOL, SYMHIB=7, FSTR=7                                
 ---  8-SPEINS: CANNOT ALLOCATE SYMBOL, SYMHIB=8, FSTR=8                                
 ---  9-PARADD: MORE THAN 9 PARAMETERS 9                                                
 --- 10-DELTA : INVALID MEMBER AT POSITION 10, 10                                         
 --- 11-PREINS: CANNOT ALLOCATE PREDECESSOR 11 OF STATE 11                                
 --- 12-STAALL: CANNOT ALLOCATE STATE 12 REACHED,SYMBOL 12                                
 --- 13-SETDEL: 13 NOT FOUND IN LIST, TAIL=13                                             
 --- 14-UNDEF : 14,14                                                                     
 --- 15-UNDEF : 15,15                                                                     
 --- 16-PROCHA: CANNOT ALLOCATE PRODUCTION OF 16, FMEM=16                                 
 --- 17-PROCHA: SAME PRODUCTION 17 FOR 17  IN THE GRAMMAR                                 
 --- 18-INFLIS: CYCLE IN LIST, AHIB=18, FA=18                                             
 --- 19-PROCHA: CANNOT ALLOCATE MEMBER, LEFT=19, FMEM=19'                                 
 --- 20-SEPUSH: CANNOT APPEND,TAIL 20, VALUE 20                                           
 --- 21-ITEALL: CANNOT ALLOCATE ITEM FOR STATE 21, ITEHIB=21                              
 --- 22-ITEINS: IN STATE 22 CANNOT INSERT POSIT 22                                        
 --- 23-PREINS: STATE 23 IS ALREADY A PREDECESSOR OF STATE 23                             
 --- 24-RECEIV: 'ALONG' DOES NOT YIELD PRODUCTION 24, BUT 24                              
 --- 25-LITRAC: ELEMENT 25 ALREADY MARKED, TAIL=25                                        
 --- 26-UNDEF : 26,26                                                                     
 --- 27-STAFRE: STATE 27 NOT IN REACHING LIST OF SYMBOL 27                                
 --- 28-SPEINS: CANNOT ALLOCATE STRING, FSTR=28, STRHIB=28                                
 --- 29-SCAN  : IN LINE 29, COLUMN 29 END OF FILE IN COMMENT                              
 --- 30-SCAN  : IN LINE 30, COLUMN 30 END OF FILE IN STRING                               
 --- 31-UNDEF : 31,31                                                                     
 --- 32-UNDEF : 32,32                                                                     
 --- 33-LITRAC: 128 LOOP CYCLES, AHEAD=33, ATAIL=33                                       
 --- 34-UNDEF : 34,34                                                                     
 --- 35-UNDEF : 35,35                                                                     
 --- 36-UNDEF : 36,36                                                                     
 --- 37-UNDEF : 37,37                                                                     
 --- 38-PARSE : STACK OVERFLOW IN STATE 38, SYMBOL 38                                     
 --- 39-PARSE : IN STATE 39 NONTERMINAL 39 NOT FOUND                                      
 --- 40-UNDEF : 40,40                                                                     
 --- 41-UNDEF : 41,41                                                                     
 --- 42-PARSER: PARSE COMPLETE. 42 ERRORS. 42                                             
 --- 43-PREINS: IN STATE 43 PREDECESSOR 43 NOT FOUND                                      
 --- 44-UNDEF : 44,44                                                                     
 --- 45-UNDEF : 45,45                                                                     
 --- 46-UNDEF : 46,46                                                                     
 --- 47-UNDEF : 47,47                                                                     
 --- 48-UNDEF : 48,48                                                                     
 --- 49-UNDEF : 49,49                                                                     
 --- 50-GRAMAR: INVALID SYMBOL 50: ''50''                                                 
 --- 51-UNDEF : 51,51                                                                     
 --- 52-UNDEF : 52,52                                                                     
 --- 53-UNDEF : 53,53                                                                     
 --- 54-UNDEF : 54,54                                                                     
 --- 55-GRAMAR: NO NUMBER AFTER ''->'', SYMBOL=55, ENTITY=55'                             
 --- 56-GRAMAR: CANNOT ALLOCATE MEMBER 56, SYMBOL=56                                      
 --- 57-GRAMAR: CANNOT ALLOCATE MEMBER 57, SYMBOL=57                                      
 --- 58-UNDEF : 58,58                                                                     
 --- 59-UNDEF : 59,59                                                                     
 --- 60-CLEARE: STATE 60 CONTAINS AT LEAST A 2ND REDUCTION 60                             
 --- 61-UNDEF : 61,61                                                                     
 --- 62-SEPANT: 62 IS NO ATTRIBUTE OF RECORD 62                                           
 --- 6363 SEMARI: INVALID OPERATION @                                                     
 --- 64-SEMARI: '*64' NOT ALLOWED HERE, REPLACED BY '*64'                                 
 --- 65-UNDEF : 65,65                                                                     
 --- 66-UNDEF : 66,66                                                                     
 --- 67-UNDEF : 67,67                                                                     
 --- 68-UNDEF : 68,68                                                                     
 --- 69-UNDEF : 69,69                                                                     
 --- 70-UNDEF : 70,70                                                                     
 --- 71-UNDEF : 71,71                                                                     
 --- 72-UNDEF : 72,72                                                                     
 --- 73-UNDEF : 73,73                                                                     
 --- 74-UNDEF : 74,74                                                                     
 --- 75-UNDEF : 75,75                                                                     
 --- 76-UNDEF : 76,76                                                                     
 --- 77-UNDEF : 77,77                                                                     
 --- 78-UNDEF : 78,78                                                                     
 --- 79-UNDEF : 79,79                                                                     
 --- 80-UNDEF : 80,80                                                                     
 --- 81-UNDEF : 81,81                                                                     
 --- 82-UNDEF : 82,82                                                                     
 --- 83-UNDEF : 83,83                                                                     
 --- 84-UNDEF : 84,84                                                                     
 --- 85-UNDEF : 85,85                                                                     
 --- 86-UNDEF : 86,86                                                                     
 --- 87-UNDEF : 87,87                                                                     
 --- 88-UNDEF : 88,88                                                                     
 --- 89-UNDEF : 89,89                                                                     
 --- 90-UNDEF : 90,90                                                                     
 --- 91-SEMWRI: INCREASE 'SEMHIB' (=91) 91                                                
 --- 9292 SEMA30: COMBINED SYMBOL @ MUST NOT BE AN ACCU WITH INCARNATION                  
 --- 93-SEMA24: RE-INPUT NOT ALLOWED AT POSITION 93 93                                    
 --- 94-SEMA27: ATTRIBUTE 94 NOT ALLOWED HERE 94                                          
 --- 95-SEMA13: RE-INPUT NOT ALLOWED AT POSITION 95 95                                    
 --- 96-SEMA14: RE-INPUT NOT ALLOWED AT POSITION 96 96                                    
 --- 97-SEMGET: SON NUMBER 97 IS NOT AN IDENTIFIER/NUMBER/STRING97                        
 --- 98-UNDEF : 98,98                                                                     
 --- 99-UNDEF : 99,99                                                                     
 ---100-UNDEF : 100,100                                                                     
 ---101-UNDEF : 101,101                                                                     
 ---102-UNDEF : 102,102                                                                     
 ---103-UNDEF : 103,103                                                                     
 ---104-UNDEF : 104,104                                                                     
 ---105-UNDEF : 105,105                                                                     
 ---106-UNDEF : 106,106                                                                     
 ---107-UNDEF : 107,107                                                                     
 ---108-UNDEF : 108,108                                                                     
 ---109-UNDEF : 109,109                                                                     
 ---110-UNDEF : 110,110                                                                     
 ---111-UNDEF : 111,111                                                                     
 ---112-UNDEF : 112,112                                                                     
 ---113-UNDEF : 113,113                                                                     
 ---114-UNDEF : 114,114                                                                     
 ---115-UNDEF : 115,115                                                                     
 ---116-UNDEF : 116,116                                                                     
 ---117-UNDEF : 117,117                                                                     
 ---118-UNDEF : 118,118                                                                     
 ---119-UNDEF : 119,119                                                                     
 ---120-UNDEF : 120,120                                                                     
 ---121-UNDEF : 121,121                                                                     
 ---122-UNDEF : 122,122                                                                     
 ---123-UNDEF : 123,123                                                                     
 ---124-UNDEF : 124,124                                                                     
 ---125-TRANS : ASSIGNMENT TO NON-EXISTING ACCU-INCARNATION 125:125                         
 ---126-TRANS-ATIN: 126 HAS NO ATTRIBUTE 126                                                
 ---127-TRANS : EXTRA-ERROR, 'ACIN' IN PRODUCTION 127, POSITION 127                         
 ---128-TRANS-SYAT: 128 HAS NO ATTRIBUTE 128                                                
 ---129-TRAPIM: INCREASE 'TRAHIB' (=129), FTRA = 129                                        
 ---130-CLEARE: 130 REDUCE- AND 130 SHIFT-ITEMS DELETED                                     
 ---131-TRANS : 'ACCU' IN PRODUCTION 131, POSITION 131                                      
 ---132-TRANS : 'ATTR' IN PRODUCTION 132, POSITION 132                                      
 ---133-TRATTR: EMPTY SON 133, ATTRIBUTE 133 IS UNDEFINED                                   
 ---134-TRATTR: 134 IS NO ENTITY, ATTRIBUTE 134 IS UNDEFINED                                
 ---135-SEMARI: ONLY ONE OPERAND FOR DYADIC OPERATION 135 135                               
 ---136-PUTCON: CONFLICT FOR 136 IN STATE 136                                               
 ---137-UNDEF : 137,137                                                                     
 ---138-TRADO : LOOP-CHECK, ACT = 138, FTRA = 138                                           
 ---139-SEPANT: INVALID ACTION NUMBER 139 139                                               
 ---140-STASYM: CANNOT FIND SYMBOL FOR STATE 140
 140                                        
 ---141-TARGET: ANCHOR NOT FOUND, ACT=141, FSTK=141                                         
 ---142-UNDEF : 142,142                                                                     
 ---143-UNDEF : 143,143                                                                     
 ---144-UNDEF : 144,144                                                                     
 ---145-LINEXT: COLUMNS 1-5 OF CONTINUATION LINE NOT BLANK 145
 145                          
 ---146-LINEXT: MORE THAN 146 CONTINUATION LINES 146                                        
 ---147-TREXPA: INCREASE STKHIB (=147)147                                                   
 ---148-PARSER: SYNTACTICAL ERROR BETWEEN 148 AND 148                                       
 ---149-ITEMA8-PAG: INCREASE DIRHIB. I2=149, STATE=149                                      
 ---150-ITEMA1-PAG: INCREASE ITEHIB. STATE=150, FITE=150                                    
 ---151-ITEMA1-PAG: TEST-INFORMATION: STATE 151 HAS 151 ITEMS                               
 ---152-ITEMA2: TEST-INFORMATION: STATE=152, STAITE()=152                                   
 ---153-DIRWRI: TEST-INFORMATION: LOW=153, HIGH=153                                         
 ---154-PARSER: TEST PANIC-MODE    FSTK=154, STATE=154                                      
 ---155-DIRECT: FDIR=155, LENGTH=155                                                        
 ---156-UNDEF : 156,156                                                                     
 ---157-UNDEF : 157,157                                                                     
 ---158-ITEMA8-PAG: TEST-INFORMATION: STATE 158 HAS 158 ITEMS                               
 ---159-ITEMA9: TEST-INFORMATION: STATE=159, STAITE()=159                                   
 ---160-UNDEF : 160,160                                                                     
 ---161-ITEMA1-NOPAG: TEST-INFORMATION: STATE 161 HAS 161 ITEMS                             
 ---162-UNDEF : 162,162                                                                     
 ---163-UNDEF : 163,163                                                                     
 ---164-UNDEF : 164,164                                                                     
 ---165-UNDEF : 165,165                                                                     
 ---166-UNDEF : 166,166                                                                     
 ---167-UNDEF : 167,167                                                                     
 ---168-ITEMA8-NOPAG: TEST-INFORMATION: STATE 168 HAS 168 ITEMS                             
 ---169-UNDEF : 169,169                                                                     
 ---170-UNDEF : 170,170                                                                     
 ---171-UNDEF : 171,171                                                                     
 ---172-UNDEF : 172,172                                                                     
 ---173-UNDEF : 173,173                                                                     
 ---174-UNDEF : 174,174                                                                     
 ---175-SEMA08: CANNOT ALLOCATE MEMBER, FMEM=175, ENTITY=175                                
 ---176-OUTPRO: LOOP-CHECK, I=176, NUC(I)=176                                               
 ---177-UNDEF : 177,177                                                                     
 ---178-UNDEF : 178,178                                                                     
 ---179-UNDEF : 179,179                                                                     
 ---180-UNDEF : 180,180                                                                     
 ---181-UNDEF : 181,181                                                                     
 ---182-UNDEF : 182,182                                                                     
 ---183-UNDEF : 183,183                                                                     
 ---184-UNDEF : 184,184                                                                     
 ---185-PUTCON: FOLLOWING CONFLICTS WERE DETECTED:185 
 185                                    
 ---186-UNDEF : 186,186                                                                     
 ---187-UNDEF : 187,187                                                                     
 ---188-UNDEF : 188,188                                                                     
 ---189-UNDEF : 189,189                                                                     
 ---190-UNDEF : 190,190                                                                     
 ---191-UNDEF : 191,191                                                                     
 ---192-UNDEF : 192,192                                                                     
 ---193-UNDEF : 193,193                                                                     
 ---194-UNDEF : 194,194                                                                     
 ---195-195 PUTCON: INCREASE PREHIB (=@)                                                    
 ---196-PUTCON: FOLLOWING TERMINALS CONTAIN UNDERSCORES: 196
 196                            
 ---197-PUTCON: CONFLICT FOR SYMBOL 197:197                                                 
 ---198-PUTCON: FOLLOWING SYMBOLS WERE NOT REACHED 198
 198                                  
 ---199-RECEXP 199,199                                                                      
 ---200-RECEXP 200,200                                                                      
