
C:\Users\User\work\gits\jextra\legacy\bofor_2005>assete
 ---  1-ALONG : IN STATE 1 POSIT 2 NOT FOUND                                            
 ---  2-HAPPEN: CANNOT ALLOCATE STRING, STRHIB=1, FSYM=2                                
 ---  3-EMITT : SYMBOL 1 IN STATE 2 NOT FOUND                                           
 ---  4-PARSE : TEST-TRACE STATE=1, ITEM=2                                              
 ---  5-SETALL: TOO MUCH SET-ELEMENTS, FSET=1, SETHIB=2                                 
 ---  6-PREDEL: STATE 1 IS NOT A PREDECESSOR OF STATE 2                                 
 ---  7-HAMAP : CANNOT ALLOCATE SYMBOL, SYMHIB=1, FSTR=2                                
 ---  8-SPEINS: CANNOT ALLOCATE SYMBOL, SYMHIB=1, FSTR=2                                
 ---  9-PARADD: MORE THAN 1 PARAMETERS 2                                                
 --- 10-DELTA : INVALID MEMBER AT POSITION 1, 2                                         
 --- 11-PREINS: CANNOT ALLOCATE PREDECESSOR 1 OF STATE 2                                
 --- 12-STAALL: CANNOT ALLOCATE STATE 1 REACHED,SYMBOL 2                                
 --- 13-SETDEL: 1 NOT FOUND IN LIST, TAIL=2                                             
 --- 14-UNDEF : 1,2                                                                     
 --- 15-UNDEF : 1,2                                                                     
 --- 16-PROCHA: CANNOT ALLOCATE PRODUCTION OF 1, FMEM=2                                 
 --- 17-PROCHA: SAME PRODUCTION 1 FOR 2  IN THE GRAMMAR                                 
 --- 18-INFLIS: CYCLE IN LIST, AHIB=1, FA=2                                             
 --- 19-PROCHA: CANNOT ALLOCATE MEMBER, LEFT=1, FMEM=2'                                 
 --- 20-SEPUSH: CANNOT APPEND,TAIL 1, VALUE 2                                           
 --- 21-ITEALL: CANNOT ALLOCATE ITEM FOR STATE 1, ITEHIB=2                              
 --- 22-ITEINS: IN STATE 1 CANNOT INSERT POSIT 2                                        
 --- 23-PREINS: STATE 1 IS ALREADY A PREDECESSOR OF STATE 2                             
 --- 24-RECEIV: 'ALONG' DOES NOT YIELD PRODUCTION 1, BUT 2                              
 --- 25-LITRAC: ELEMENT 1 ALREADY MARKED, TAIL=2                                        
 --- 26-UNDEF : 1,2                                                                     
 --- 27-STAFRE: STATE 1 NOT IN REACHING LIST OF SYMBOL 2                                
 --- 28-SPEINS: CANNOT ALLOCATE STRING, FSTR=1, STRHIB=2                                
 --- 29-SCAN  : IN LINE 1, COLUMN 2 END OF FILE IN COMMENT                              
 --- 30-SCAN  : IN LINE 1, COLUMN 2 END OF FILE IN STRING                               
 --- 31-UNDEF : 1,2                                                                     
 --- 32-UNDEF : 1,2                                                                     
 ---201-ASSERT: MORE THAN  32 ASSERTIONS - STOP
