      SUBROUTINE ALONG(STATEQ,POSQ,STATE,PROD)
C     WALK THROUGH THE STATES AND MOVE THE MARKER BEHIND A PRODUCTION
C     GF 20.08.1980 : WITH CALL 'DELTA'
C
      INCLUDE 'PARS.f'
      INCLUDE 'ITES.f'
      INCLUDE 'MEMS.f'
      INCLUDE 'STAS.f'
      INTEGER*2 I
     = ,ACTION  ! RESULT OF 'DELTA'
     = ,POS      ! TEMPORARY POSIT OF THE MARKER
     = ,POSQ     ! START WITH THIS POSIT AND MOVE THE MARKER,THE END
     = ,PROD     ! RESULTING PRODUCTION
     = ,STATE    ! THE STATE THAT HAS THE MARKER AT THE END, OR 0
     = ,STATEQ   ! THIS STATE HAS AN ITEM WITH THE MARKER BEFORE 'POSQ'
     = ,SUCPRO  ! RESULT OF 'DELTA', NEXT 'STATE'
     = ,SYMBOL   !  = MEM(POS)
C
      STATE = STATEQ ! BEGIN WITH THIS 'STATE'
      POS = POSQ
      SYMBOL = MEM(POS)
1     IF(SYMBOL   .LE. 1) GOTO 2 ! DUMMY SYMBOL NOT YET REACHED
        CALL DELTA (STATE,SYMBOL,  ACTION,SUCPRO)
        STATE = SUCPRO
        IF (ACTION .NE. SHIFT) GOTO 7
          IF (STATE .LT. 0)  !,BE PROCESSED,'STASUC'
     =      STATE = 0
          IF (STATE .EQ. 0)! SUCCESSOR NOT YET COMPUTED
     =      GOTO 101
          POS = POS + 1
          SYMBOL = MEM(POS)
          GOTO 100 ! THIS MEMBER WAS FOUND
7       CONTINUE ! SHIFT
        ! 'POS' WAS NOT FOUND IN 'STATE' :
        CALL ASSERT(1,STATE,POS)
        STATE = 0
        GOTO 101
C
100     CONTINUE !      LEAVE
      GOTO 1
2     CONTINUE ! WHILE DUMMY SYMBOL NOT REACHED
      PROD = MEMNUC(POS)
      ! 'STATE' IS ALREADY O.K.
C
101   CONTINUE !     DONE
CXML
C     XML4 (ALONG, STATEQ, POSQ, STATE, PROD)
      CALL XML4 ('ALONG', 1, 5, STATEQ,POSQ,STATE,PROD)
      RETURN! ALONG
      END
