C     ASSETE: PROCEDURE OPTIONS(MAIN);
C     TEST 'ASSERT' BY PRINTING ALL MESSAGES 
C     2005-04-07, Georg Fischer
C
      INTEGER*2 I
C
      DO 10 I = 1, 200
        CALL ASSERT(I,1,2)
 10   CONTINUE
      END ! ASSETE;
