      SUBROUTINE ASSERT(NUM,VAR1,VAR2)
C     PRINT AN ERROR- OR OTHER MESSAGE OF THE EXTRA-SYSTEM
C     2022-02-05: OPEN statement for gfortran
C     GF 21.07.1980
C
      INCLUDE 'PARS.F'
      INTEGER*2 PARASK
      INTEGER*2 RECLEN
      PARAMETER RECLEN=80
      INTEGER*2 ZZINDX
      INTEGER*2 I
     = ,MAX   ! NO MORE CALLS ARE ALLOWED
     = ,NOW   ! HOW OFTEN WAS 'ASSERT' CALLED
     = ,NUM      ! THE NUMBER OF THE MESSAGE
     = ,P1       ! LENGTH OF
     = ,P2       ! LENGTH OF THE 2ND PORTION OF TEXT
     = ,T(40)   ! BUFFER FOR THE TEXTS
     = ,VAR1     ! 1ST VARIABLE,BE INSERTED IN THE TEXT
     = ,VAR2     ! 2ND ...
      DATA MAX /0/, NOW/0/
      INCLUDE 'ENDS.F'
C
      IF (MAX .GT. 0) GOTO 10
        MAX = PARASK('ASSERT',1,6,32)
10    CONTINUE
      OPEN (UNIT=UASS,file='ASSTEX.DIR',ACCESS='DIRECT'
     = ,status='OLD',RECL=RECLEN)
C     the following lines are read by ASSLOA and stored in UDIR
C----------------
C=  1: ALONG : IN STATE @ POSIT @ NOT FOUND
C=  2: HAPPEN: CANNOT ALLOCATE STRING, STRHIB=@, FSYM=@
C=  3: EMITT : SYMBOL @ IN STATE @ NOT FOUND
C=  4: PARSE : TEST-TRACE STATE=@, ITEM=@
C=  5: SETALL: TOO MUCH SET-ELEMENTS, FSET=@, SETHIB=@
C=  6: PREDEL: STATE @ IS NOT A PREDECESSOR OF STATE @
C=  7: HAMAP : CANNOT ALLOCATE SYMBOL, SYMHIB=@, FSTR=@
C=  8: SPEINS: CANNOT ALLOCATE SYMBOL, SYMHIB=@, FSTR=@
C=  9: PARADD: MORE THAN @ PARAMETERS @
C= 10: DELTA : INVALID MEMBER AT POSITION @, @
C= 11: PREINS: CANNOT ALLOCATE PREDECESSOR @ OF STATE @
C= 12: STAALL: CANNOT ALLOCATE STATE @ REACHED,SYMBOL @
C= 13: SETDEL: @ NOT FOUND IN LIST, TAIL=@
C= 16: PROCHA: CANNOT ALLOCATE PRODUCTION OF @, FMEM=@
C= 17: PROCHA: SAME PRODUCTION @ FOR @  IN THE GRAMMAR
C= 18: INFLIS: CYCLE IN LIST, AHIB=@, FA=@
C= 19: PROCHA: CANNOT ALLOCATE MEMBER, LEFT=@, FMEM=@'
C= 20: SEPUSH: CANNOT APPEND,TAIL @, VALUE @
C= 21: ITEALL: CANNOT ALLOCATE ITEM FOR STATE @, ITEHIB=@
C= 22: ITEINS: IN STATE @ CANNOT INSERT POSIT @
C= 23: PREINS: STATE @ IS ALREADY A PREDECESSOR OF STATE @
C= 24: RECEIV: 'ALONG' DOES NOT YIELD PRODUCTION @, BUT @
C= 25: LITRAC: ELEMENT @ ALREADY MARKED, TAIL=@
C= 27: STAFRE: STATE @ NOT IN REACHING LIST OF SYMBOL @
C= 28: SPEINS: CANNOT ALLOCATE STRING, FSTR=@, STRHIB=@
C= 29: SCAN  : IN LINE @, COLUMN @ END OF FILE IN COMMENT
C= 30: SCAN  : IN LINE @, COLUMN @ END OF FILE IN STRING
C= 33: LITRAC: 128 LOOP CYCLES, AHEAD=@, ATAIL=@
C= 38: PARSE : STACK OVERFLOW IN STATE @, SYMBOL @
C= 39: PARSE : IN STATE @ NONTERMINAL @ NOT FOUND
C= 42: PARSER: PARSE COMPLETE. @ ERRORS. @
C= 43: PREINS: IN STATE @ PREDECESSOR @ NOT FOUND
C= 50: GRAMAR: INVALID SYMBOL @: ''@''
C= 55: GRAMAR: NO NUMBER AFTER ''->'', SYMBOL=@, ENTITY=@'
C= 56: GRAMAR: CANNOT ALLOCATE MEMBER @, SYMBOL=@
C= 57: GRAMAR: CANNOT ALLOCATE MEMBER @, SYMBOL=@
C= 60: CLEARE: STATE @ CONTAINS AT LEAST A 2ND REDUCTION @
C= 62: SEPANT: @ IS NO ATTRIBUTE OF RECORD @
C= 63: SEMARI: INVALID OPERATION @ @
C= 64: SEMARI: '*@' NOT ALLOWED HERE, REPLACED BY '*@'
C= 91: SEMWRI: INCREASE 'SEMHIB' (=@) @
C= 92: SEMA30: COMBINED SYMBOL @ MUST NOT BE AN ACCU WITH INCARNATION @
C= 93: SEMA24: RE-INPUT NOT ALLOWED AT POSITION @ @
C= 94: SEMA27: ATTRIBUTE @ NOT ALLOWED HERE @
C= 95: SEMA13: RE-INPUT NOT ALLOWED AT POSITION @ @
C= 96: SEMA14: RE-INPUT NOT ALLOWED AT POSITION @ @
C= 97: SEMGET: SON NUMBER @ IS NOT AN IDENTIFIER/NUMBER/STRING@
C=125: TRANS : ASSIGNMENT TO NON-EXISTING ACCU-INCARNATION @:@
C=126: TRANS-ATIN: @ HAS NO ATTRIBUTE @
C=127: TRANS : EXTRA-ERROR, 'ACIN' IN PRODUCTION @, POSITION @
C=128: TRANS-SYAT: @ HAS NO ATTRIBUTE @
C=129: TRAPIM: INCREASE 'TRAHIB' (=@), FTRA = @
C=130: CLEARE: @ REDUCE- AND @ SHIFT-ITEMS DELETED
C=131: TRANS : 'ACCU' IN PRODUCTION @, POSITION @
C=132: TRANS : 'ATTR' IN PRODUCTION @, POSITION @
C=133: TRATTR: EMPTY SON @, ATTRIBUTE @ IS UNDEFINED
C=134: TRATTR: @ IS NO ENTITY, ATTRIBUTE @ IS UNDEFINED
C=135: SEMARI: ONLY ONE OPERAND FOR DYADIC OPERATION @ @
C=136: PUTCON: CONFLICT FOR @ IN STATE @
C=138: TRADO : LOOP-CHECK, ACT = @, FTRA = @
C=139: SEPANT: INVALID ACTION NUMBER @ @
C=140: STASYM: CANNOT FIND SYMBOL FOR STATE @ @
C=141: TARGET: ANCHOR NOT FOUND, ACT=@, FSTK=@
C=145: LINEXT: COLUMNS 1-5 OF CONTINUATION LINE NOT BLANK @ @
C=146: LINEXT: MORE THAN @ CONTINUATION LINES @
C=147: TREXPA: INCREASE STKHIB (=@)@
C=148: PARSER: SYNTACTICAL ERROR BETWEEN @ AND @
C=149: ITEMA8-PAG: INCREASE DIRHIB. I2=@, STATE=@
C=150: ITEMA1-PAG: INCREASE ITEHIB. STATE=@, FITE=@
C=151: ITEMA1-PAG: TEST-INFORMATION: STATE @ HAS @ ITEMS
C=152: ITEMA2: TEST-INFORMATION: STATE=@, STAITE()=@
C=153: DIRWRI: TEST-INFORMATION: LOW=@, HIGH=@
C=154: PARSER: TEST PANIC-MODE    FSTK=@, STATE=@
C=155: DIRECT: FDIR=@, LENGTH=@
C=158: ITEMA8-PAG: TEST-INFORMATION: STATE @ HAS @ ITEMS
C=159: ITEMA9: TEST-INFORMATION: STATE=@, STAITE()=@
C=161: ITEMA1-NOPAG: TEST-INFORMATION: STATE @ HAS @ ITEMS
C=168: ITEMA8-NOPAG: TEST-INFORMATION: STATE @ HAS @ ITEMS
C=175: SEMA08: CANNOT ALLOCATE MEMBER, FMEM=@, ENTITY=@
C=176: OUTPRO: LOOP-CHECK, I=@, NUC(I)=@
C=185: PUTCON: FOLLOWING CONFLICTS WERE DETECTED: @ @
C=195: PUTCON: INCREASE PREHIB (=@)
C=196: PUTCON: FOLLOWING TERMINALS CONTAIN UNDERSCORES: @ @
C=197: PUTCON: CONFLICT FOR SYMBOL @:@
C=198: PUTCON: FOLLOWING SYMBOLS WERE NOT REACHED @ @
C=199: RECEXP @,@
C=200: RECEXP @,@
C----------------
      I = 29647
      IF (PARASK('TRASSE',1,6,0) .EQ. 0) GOTO 12
        WRITE (UPRI,11) NUM, VAR1, VAR2
11      FORMAT(1X,'TRASSE: ', I3,I6,I6)
        RETURN
12    CONTINUE
      NOW = NOW + 1
      IF (NOW .GT. MAX) GOTO 1
        I = NUM
        READ (UASS,REC=NUM) (T(P1),P1=1,40)
        P1 = ZZINDX(T,1,80,'@')
        P2 = ZZINDX(T,P1+1,80,'@')
        ! <---P1------>
        ! <------P2------------------>
        !    LEFT     @     MIDDLE   @    RIGHT
        CALL ZZWC ('---',1,3,0)
        CALL ZZWI (NUM,3)
        CALL ZZWC ('-',1,1,0)
        CALL ZZWC (T,2,P1-1,0)
        IF (VAR1 .EQ. 0) GOTO 3
          IF (VAR1 .GE. 0) GOTO 4
            CALL PUTSYM(-VAR1)
          GOTO 5
4         CONTINUE
            CALL ZZWI (VAR1,0)
5         CONTINUE
          CALL ZZWC (T,P1+1,P2-1,0)
          IF (VAR2 .EQ. 0) GOTO 6
            IF (VAR2 .GE. 0 ) GOTO 7
              CALL PUTSYM(-VAR2)
            GOTO 8
7           CONTINUE
              CALL ZZWI (VAR2,0)
8           CONTINUE
            CALL ZZWC (T,P2+1,80,0)
6         CONTINUE ! VAR2 .EQ. 0
3       CONTINUE ! VAR1 .EQ. 0
        CALL ZZWS (0)
        CLOSE (UNIT=UASS)
      GOTO 2
1     CONTINUE ! NOW .GT. MAX
        WRITE(*,9) MAX
9       FORMAT(' ---201-ASSERT: MORE THAN ',I3,' ASSERTIONS - STOP')
        STOP
2     CONTINUE ! NOW .LE.  MAX
      RETURN
      END
