      SUBROUTINE CODASS(CHARN,CHARS,CHARE,CODE)
C     ASSIGN A 'CODE' FOR ALL CHARACTERS OF 'CHARS'
C
      INCLUDE 'PARS.f'
      INCLUDE 'CODS.f'
      INTEGER*2 I
     = ,CHARS   ! 1ST POS IN 'CHARS'
     = ,CHARE   ! LAST ...
     = ,CHARN (1) ! ASSIGN 'CODE' TO THESE CHARACTERS
     = ,CODE    ! CODE TO BE ASSIGNED
     = ,TABPOS   ! CORRESPONDS,THE FIXED VALUE OF THE CHARACTER IN 'CH2'
C
      CODE = FCOD
      FCOD = FCOD + 1
      DO 2 I = CHARS,CHARE
        CALL ZZCI(CHARN,I,TABPOS)
        TABPOS = TABPOS + 1
        CODTAB(TABPOS) = CODE
2     CONTINUE
      RETURN ! CODASS
      END
