      SUBROUTINE CODGET
C     GET THE CODE OF THE NEXT CHARACTER IN THE INPUT
C
      INCLUDE 'PARS.f'
      INCLUDE 'CODS.f'
      INCLUDE 'LINS.f'
C
      CALL ZZCI (LINE,FLIN,SC)
      FLIN = FLIN + 1
      SC = SC + 1
      SC = CODTAB(SC)
      RETURN
      END
