      SUBROUTINE DAWRTE (ARRAY,RECNO)
C     WRITE DIRECT-FILE
C     2022-02-05: include DIRS.F, formal parms DECB, FDIR4 -> COMMON 
C     GF 15.10.2002
C
      INCLUDE 'PARS.f'
      INCLUDE 'DIRS.f'
      INTEGER*2 I
     = ,ARRAY(1) ! TRANSMIT FROM/TO THIS ARRAY
C     = ,DECB(1) ! IGNORE
C      INTEGER*4 FDIR4
      INTEGER*2 RECNO
      INTEGER*4 OFFSET
C
      OFFSET = FDIR4*DIRHIB/2
      CALL FSEEK (UDIR, OFFSET, 0)
      WRITE  (UDIR) (ARRAY(I),I=1,DIRHIB/2)
      RETURN
 99   CONTINUE
      PRINT *, 'ERROR IN DAWRTE'
      RETURN
C     
      ENTRY      DAREAD (ARRAY,RECNO)
C     READ  DIRECT-FILE
C     GF 15.10.2002
C
      OFFSET = FDIR4*DIRHIB/2
      CALL FSEEK (UDIR, OFFSET, 0)
      READ   (UDIR) (ARRAY(I),I=1,DIRHIB/2)
      RETURN
C      
      ENTRY DAWAIT ()
      RETURN
      END
