      SUBROUTINE DAWRTE (DECB,ARRAY,FDIR4,RECNO)
C     WRITE DIRECT-FILE
C     GF 15.10.2002
C
      INCLUDE 'PARS.F'
      INTEGER*2 I
     = ,DECB(1) ! IGNORE
     = ,ARRAY(1) ! TRANSMIT FROM/TO THIS ARRAY
      INTEGER*4 FDIR4
      INTEGER*2 RECNO
      INTEGER*4 OFFSET
C
      OFFSET = FDIR4*DIRHIB/2
      CALL FSEEK (UDIR, OFFSET, 0)
      WRITE  (UDIR) (ARRAY(I),I=1,DIRHIB/2)
      RETURN
 99   CONTINUE
      PRINT *, 'ERROR IN DAWRTE'
      RETURN
C     
      ENTRY      DAREAD (DECB,ARRAY,FDIR4,RECNO)
C     READ  DIRECT-FILE
C     GF 15.10.2002
C
      OFFSET = FDIR4*DIRHIB/2
      CALL FSEEK (UDIR, OFFSET, 0)
      READ   (UDIR) (ARRAY(I),I=1,DIRHIB/2)
      RETURN
C      
      ENTRY DAWAIT (DECB)
      RETURN
      END
