C-------GF 18.09.1980--------------------------------------- D I R S
      INTEGER*2 FDIR,DIRHIB,LOW,HIGH
      INTEGER*2 DECB(5)
      INTEGER*4 FDIR4
      COMMON /AAAAAA/  ! BEFORE ALL OTHER COMMONS
     =  FDIR    ! NEXT FREE RECORD (=ASSOCIATE VARIABLE)
     = ,DIRHIB  ! LENGTH OF A RECORD IN INTEGER-ELEMENTS
     = ,LOW     ! -> ARRAY-ELEMENT WHICH COMES IN LOW BUFFER
     = ,HIGH    ! ... HIGH ...
     = ,DECB    ! DATA-EVENT CONTROL BLOCK FOR 'DAIO'
     = ,FDIR4   ! BLOCK NUMBER FOR 'DAIO'
