C-------GF 2022-02-07--------------------------------------- D I R S
      INTEGER*2 FDIR,DIRHIB,LOW,HIGH
      COMMON /AAAAAA/  ! BEFORE ALL OTHER COMMONS
     =  FDIR    ! NEXT FREE RECORD (=ASSOCIATE VARIABLE)
     = ,DIRHIB  ! LENGTH OF A RECORD IN INTEGER-ELEMENTS
     = ,LOW     ! -> ARRAY-ELEMENT WHICH COMES IN LOW BUFFER
     = ,HIGH    ! ... HIGH ...
