      SUBROUTINE HAINIT
C     INITIALIZE 'STRS' AND 'BUCS'
C
      INCLUDE 'PARS.F'
      INCLUDE 'BUCS.F'
      INCLUDE 'STRS.F'
      INCLUDE 'SYMS.F'
      INTEGER*2 I
C
      FSTR = 2
      SYMPOS(FSYM) = FSTR ! ALWAYS, FOR 'HAMAP'
      DO 7 I = 1, BUCHIB
        BUCKET(I) = SYMHIB ! ALL LISTS ARE EMPTY
7     CONTINUE !,BUCHIB
      RETURN ! HAINIT
      END
