      SUBROUTINE HAPSE (CHARN,CHARS,CHARE)
C     APPEND A STRING TO THE SYMBOL IN SPE
C
      INCLUDE 'PARS.f'
      INCLUDE 'STRS.f'
      INCLUDE 'SYMS.f'
      INTEGER*2 CHARS,CHARE,CHARN(1)
     = ,LNGPEN  ! THE LENGTH OF THE STRING TO BE APPENDED
C
      LNGPEN = CHARE - CHARS + 1
      IF (LNGPEN .LE. 0)
     =  RETURN
      IF (FSTR + LNGPEN .GT. STRHIB) GOTO 8
        CALL ZZCC (CHARN,CHARS,CHARE,STRNG,FSTR,FSTR+LNGPEN-1)
        FSTR = FSTR + LNGPEN
      GOTO 9
8     CONTINUE
        CALL ASSERT(2,STRHIB,FSYM)
9     CONTINUE
      RETURN ! HAPSE
      END
