      SUBROUTINE HEADER (FILE,FILNG,PAGE)
C     WRITES A HEADER ON THE LISTING FILE
C     GF 27.07.1980
C
      INCLUDE 'PARS.F'
      INTEGER*2 I
     = ,FILE(10)  ! THE NAME OF THE SOURCE-FILE
     = ,FILNG   ! LENGTH OF THE FILE-NAME 'FILE'
     = ,PAGE      ! CURRENT PAGE-NUMBER OF THE LISTING
     = ,TEXT(4)   ! STORE TIME HERE
     = ,TEXD(5)   ! STORE DATE HERE
      CALL ZZCC ('19:54:00',1,8,TEXT,1,8)
      CALL ZZCC ('15.20.2002',1,10,TEXD,1,10)
      WRITE (UPRI,1) TEXT,TEXD,PAGE
1     FORMAT('1BOFOR PRECOMPILER V01-03        '
     = ,4A2,4X,4A2,A1,10X,'PAGE',I3
     = )
      CALL ZZWC(FILE,1,FILNG,0)
      CALL ZZWS (0)
      CALL ZZWC(' ',1,1,0)
      CALL ZZWS (0)
      RETURN
      END
