      INTEGER*2 XXINFH
      PARAMETER (XXINFH=10)
      INTEGER*2 INFORM(XXINFH)
      INTEGER*2 INFMAX(XXINFH)
      INTEGER*2 INFNUM(XXINFH)
      INTEGER*2    INFBEG(XXINFH),INFSUM(XXINFH)
      COMMON /INFS/
     =  INFORM  ! STORE STATISTICS IN THIS ARRAY
     = ,INFMAX  ! 'INFORM' IS ALWAYS < 'INFMAX'
     = ,INFBEG  ! CPU-TIME AT THE BEGINNING
     = ,INFSUM  ! CUMMULATIVE CPU-TIME
     = ,INFNUM  ! NUMBER OF CALLS OF 'INFTIM(ORD)'
