      SUBROUTINE ITEINS(STATE,POSIT,SYMEX,ITEMEX)
C     INSERT AN ITEM IN A STATE
C     GF 11.07.1980
C
      INCLUDE 'PARS.F'
      INCLUDE 'ITES.F'
      INCLUDE 'MEMS.F'
      INCLUDE 'SETS.F'
      INCLUDE 'STAS.F'
      INTEGER*2 PARASK
      INTEGER*2 D
     = ,DIFF1    !,COMPARE THE SYMBOLS
     = ,DIFF2    !,COMPARE THE ACTIONS
     = ,DIFF3    !,COMPARE THE POSITS
     = ,GOT     ! RESULT OF 'ITEMA2'
     = ,I1       ! -> ONE ELEMENT BEFORE THE ELEMENT INSPECTED
     = ,I2       ! THE CURRENT ITEM INSPECTED
     = ,ITEM     ! -> THE ITEM FINALLY INSERTED
     = ,ITEMA    ! -> THE ITEM WHERE A SYMBOL OCCURED FIRST
     = ,ITEMEX   ! .LE. 0 IF (THE ITEM DID NOT EXIST IN 'STATE'
     = ,POSIT ! INSERT AN ITEM WITH THE MARKER BEFORE THIS POSITION
     = ,STATE    ! INSERT THE ITEM IN THIS STATE
     = ,SYMA     ! THE MARKED SYMBOL OF THE ITEM 'ITEMA'
     = ,SYMBOL   ! THE MARKED SYMBOL
     = ,SYMEX    ! .LE. 0 IF (THE MARKED SYMBOL DID NOT EXIST IN 'STATE'
C
      ITEMEX = 0
      SYMBOL = MEM(POSIT)
      SYMEX = SYMBOL
      CALL ITEMA2 (STATE,  I1,I2,GOT)
      ITEMA = I2
      SYMA = ITESYM(ITEMA)!
5     IF(I1 .GE. ITEHIB) GOTO 6
        DIFF1 = SYMBOL - ITESYM(I2)
        IF (DIFF1 .GE. 0) GOTO 7 ! SYMBOL .GE.
          CALL SEPUSH(STAMAR,STATE,LAPUTT,LAPUTB)
          GOTO 100
C       GOTO 8 ! SYMBOL .GE.
7       CONTINUE
        IF (DIFF1 .NE. 0) GOTO 9 ! SYMBOL =
          SYMEX = 0
          DIFF2 = SHIFT - ITEACT(I2)
          IF (DIFF2 .GE. 0) GOTO 10 ! SHIFT .GE. REDUCE
            CALL SEPUSH(STAMAR,STATE,SPLITT,SPLITB)
            GOTO 100
C         GOTO 13 ! SHIFT .GE. REDUCE
10        CONTINUE
          ! ACTION = (SHIFT), ACTION .LE. NOT POSSIBLE
            DIFF3 =  POSIT - ITEPOS(I2)
            IF (DIFF3 .GE. 0) GOTO 11 ! POSIT .GE.
              GOTO 100
C           CONTINUE ! POSIT .GE.
11          CONTINUE
            IF (DIFF3 .NE. 0) GOTO 12 ! POSIT =
              ITEMEX = I2
              GOTO 101
12          CONTINUE ! POSIT =
            ! ELSE POSIT > : TRY NEXT ELEMENT
13        CONTINUE ! ACTION =
          ! ELSE ACTION > : NOT POSSIBLE
9       CONTINUE ! SYMBOL =
8       CONTINUE
        ! ELSE SYMBOL > : TRY NEXT ELEMENT
        IF (ITESYM(I2) .EQ. SYMA) GOTO 14
          ITEMA = I2
          SYMA = ITESYM(ITEMA)!
14      CONTINUE
        I1 = I2
        I2 = ITE(I1)!
      GOTO 5
6     CONTINUE ! ALL ITEMS
      CALL ASSERT(22,STATE,POSIT) ! NO PLACE FOUND WHERE,INSERT
C
100   CONTINUE !      INSERT:
      CALL ITEALL (SYMBOL,POSIT,SHIFT,0,  I1,I2)
      IF (SYMBOL .LE. 1) GOTO 15
        CALL SEPUSH(STAMAR,STATE,STASUT,STASUB)
      GOTO 16
15    CONTINUE
        CALL SEPUSH(STAMAR,STATE,LAGETT,LAGETB)
16    CONTINUE ! SYMBOL .GT. 1
C
101   CONTINUE !      DONE:
      CALL ITEMA9 (STATE,GOT)
CXML
C     XML4 (ITEINS, STATE, POSIT, SYMEX, ITEMEX)
      CALL XML4 ('ITEINS', 1, 6, STATE,POSIT,SYMEX,ITEMEX)
      RETURN! ITEINS
      END
