      SUBROUTINE ITEMA9 (STATE,GOT)
C     WRITE AND UNLOCK AN ITEM-SET
C     GF 20.08.1980
C
      INCLUDE 'PARS.F'
      INCLUDE 'ITES.F'
      INCLUDE 'SLOS.F'
      INTEGER*2 DIR(XXDIRH)
      EQUIVALENCE (SLOT(1,1),DIR(1))
      INCLUDE 'DIRS.F'
      INCLUDE 'STAS.F'
      INTEGER*2 PARASK
      INTEGER*2 I1,I2
     = ,GOT     ! = 1 (0) IF THE STATE WAS (NOT) REALLY READ
     = ,STATE   ! ACCESS TO THIS ITEM-SET
C
      STAITE(STATE) = ITE(1)
      RETURN
C--------
      IF (STATE .NE. 0) GOTO 1
        WRITE (UPRI,2) -999
2       FORMAT (1X,I1)
        RETURN
1     CONTINUE
      STAITE(STATE) = ITE(1) ! ANCHOR MAY BE CHANGED
      IF (GOT .EQ. 0) RETURN
      CALL ITEMA8 (STATE,GOT)
      IF (ITEPAG .GT. 1 .OR. ITEPAG .LT. 0)
     =  CALL ASSERT (159,STATE,STAITE(STATE))
      IF (ITEPAG .LE. 0) GOTO 85
        FDIR = STATE
        CALL DIRWRI (DIR,DIRHIB)
85    CONTINUE
      RETURN
      END
