      SUBROUTINE LAGET
C     GET LOOK-AHEAD SYMBOLS FOR ALL PRODUCTIONS OF ALL STATES IN QUEU
C     2005-03-29: demingle MEMSETS
C
      INCLUDE 'PARS.f'
      INCLUDE 'ITES.f'
      INCLUDE 'MEMS.f'
      INCLUDE 'SETS.f'
      INCLUDE 'STAS.f'
      INTEGER*2 I
     = ,ENBLOC   ! = 0 (1) FOR A INCREMENTAL (EN-BLOC) CONSTRUCTION
     = ,GOT     ! RESULT OF 'ITEMA1/2', =1 IF STATE WAS READ
     = ,I1       ! -> ITEM BEFORE ITEM 'I2'
     = ,I2       ! CURRENT ITEM IN 'STATEZ'
     = ,STATEZ   ! A STATE FROM THE QUEUE
      INTEGER*2 PARASK
      EXTERNAL LACOPY
C
      ENBLOC = PARASK ('ENBLOC',1,6,0)
1     IF(LAGETH .EQ. LAGETT) GOTO 2 ! FOR ALL ELEMENTS OF THE QUEUE
        CALL SETPOP(STAMAR,STATEZ,LAGETH,LAGETB)
        CALL ITEMA2 (STATEZ,  I1,I2,GOT)
3       IF(ITESYM(I2) .NE. 1) GOTO 4 ! ALL REDUCTIONS TO BE PROCESSED
          IF (ENBLOC .NE. 1)
     =      CALL EMITT(STATEZ,MEMNUC(ITEPOS(I2)),LACOPY)
          CALL ITEFRE (  I1,I2) ! DELETE THE DUMMY SYMBOL
          I1 = I2
          I2 = ITE(I1)!
        GOTO 3
4       CONTINUE ! ALL DUMMY SYMBOLS
C
        CALL ITEMA9 (STATEZ,GOT)
      GOTO 1
2     CONTINUE ! ALL IN QUEUE
      RETURN! LAGET
      END
