      SUBROUTINE LAPUT
C     PROPAGATE THE SYMBOLS OF ALL STATES IN THE QUEUE
C
      INCLUDE 'PARS.f'
      INCLUDE 'SETS.f'
      INCLUDE 'STAS.f'
      INTEGER*2 I
     = ,STATEB   ! A STATE OF THE QUEUE
      EXTERNAL LACOPY
C
      I = FSTA - 1
      DO 7 STATEB=2,I
        CALL SEPUSH (STAMAR,STATEB,LAPUTT,LAPUTB)
7     CONTINUE
5     IF(LAPUTH .EQ. LAPUTT) GOTO 6
        CALL SETPOP(STAMAR,STATEB,LAPUTH,LAPUTB)
CXML
C       XML1 (LAPUT, STATEB)
        CALL XML1 ('LAPUT', 1, 5, STATEB)
        CALL RECEIV(STATEB,LACOPY)
      GOTO 5
6     CONTINUE ! ALL IN QUEUE
      RETURN! LAPUT
      END
