      SUBROUTINE LINIT
C     INITIALIZE READING OF SOURCE-TEXT
C
      INCLUDE 'PARS.f'
      INCLUDE 'LINS.f'
      INTEGER*2 I
C
      LIMARL =  1
      LIMARR = (XXLINH - 1) * 2
      LIEOFC = 127
      CALL ZZCI ('!',1,LIEOLC)
      CALL ZZIC (LIEOFC,LINE,1)
      CALL CODASS (LINE,1,1,I) ! THROW 'I'
      CALL ZZIC (LIEOLC,LINE,1)
      CALL CODASS (LINE,1,1,I)
      LINENO = 0 ! 1ST NOT YET READ IN
      LILANG = 1 ! PL/1
      CALL LINEXT
      RETURN
      END
