C-------GF 01.08.1980------------------------------- L I N S
      INTEGER*2 FLIN,LINENO,LINE(XXLINH)
      INTEGER*2 LIMARL,LIMARR,LIEOFC,LIEOLC
      INTEGER*2 LINOCO,LILANG
      COMMON /LINS/
     =  FLIN    ! 1ST COLUMN NOT YET PROCESSED BY 'SCAN'
     = ,LINENO  ! SEQUENTIAL NUMBER OF THE LINE
     = ,LINE    ! BUFFER FOR THE LINE + 1 STOP-CHARACTER
     = ,LIMARL  ! LEFT MARGIN OF SOURCE-LINE
     = ,LIMARR  ! RIGTH ...
     = ,LIEOFC  ! A CHARACTER WHICH INDICATES THE END OF FILE
     = ,LIEOLC  ! ... END OF LINE
     = ,LINOCO  ! NUMBER OF CONTINUATION LINES
     = ,LILANG  ! = 1,2,3: LANGUAGE IS PL/1, FORTRAN, COBOL
C     LIEOFC .AND. (FLIN=1 => EOFILE, FLIN=LINHIB => EOSTMT)
