C-------GF 28.08.1980------------------------ M E M S E T S
      INTEGER*2 FSET,SETHIB
      INTEGER*2 SET   (XXSETH),SETELE(XXSETH)
     = ,EMITSH,EMITST,EMITSB   ! STA: FOR EMITT, SOURCE
     = ,EMITTH,EMITTT,EMITTB   ! STA: FOR EMITT, TARGET
     = ,LAGARH,LAGART,LAGARB   ! STA: FOR LAGAR
     = ,LAGETH,LAGETT,LAGETB   ! STA: FOR LAGET
     = ,LAPUTH,LAPUTT,LAPUTB   ! STA: FOR LAPUT
     = ,SPLITH,SPLITT,SPLITB   ! STA: FOR SPLIT
     = ,STACLH,STACLT,STACLB   ! SYM: FOR STACLO
     = ,STAGAH,STAGAT,STAGAB   ! STA: FOR STAGAR, ILL STATES
     = ,STAGBH,STAGBT,STAGBB   ! STA: FOR STAGAR, SURVIVING STATES
     = ,STASUH,STASUT,STASUB   ! STA: FOR STASUC
     = ,SYMINH,SYMINT,SYMINB   ! SYM: FOR SYMINS
      COMMON /SETS/
     =  FSET
     = ,SETHIB
     = ,EMITSH,EMITST,EMITSB   ! STA: FOR EMITT, SOURCE
     = ,EMITTH,EMITTT,EMITTB   ! STA: FOR EMITT, TARGET
     = ,LAGARH,LAGART,LAGARB   ! STA: FOR LAGAR
     = ,LAGETH,LAGETT,LAGETB   ! STA: FOR LAGET
     = ,LAPUTH,LAPUTT,LAPUTB   ! STA: FOR LAPUT
     = ,SPLITH,SPLITT,SPLITB   ! STA: FOR SPLIT
     = ,STACLH,STACLT,STACLB   ! SYM: FOR STACLO
     = ,STAGAH,STAGAT,STAGAB   ! STA: FOR STAGAR, ILL STATES
     = ,STAGBH,STAGBT,STAGBB   ! STA: FOR STAGAR, SURVIVING STATES
     = ,STASUH,STASUT,STASUB   ! STA: FOR STASUC
     = ,SYMINH,SYMINT,SYMINB   ! SYM: FOR SYMINS
      COMMON /SETTRA/ SETELE
      EQUIVALENCE (SET(1),MEMNUC(1))
