      SUBROUTINE OUTSET(ELEM)
C     OUTPUT A SINGLE ELEMENT OF A SET (PARAMETER TO 'LITRAC')
C     2005-05-06: LINE BREAK AFTER 8 ELEMENTS
C
      INCLUDE 'PARS.f'
      INCLUDE 'SETS.f'
      INTEGER*2 ELEM
C
      OUTSC = OUTSC + 1
      IF (MOD(OUTSC, 8) .NE. 1) GOTO 10
        CALL ZZWS(0)
        CALL ZZWC('    ', 1, 4, 0)
10    CONTINUE
      CALL ZZWI(SETELE(ELEM),4)
      RETURN
      END
