      INTEGER*2 FUNCTION PARASK (CHARN,CHARS,CHARE,DEFLT)
C     RETURN THE VALUE OF A SYSTEM-PARAMETER
C
      INCLUDE 'PARS.F'
      INTEGER*2 ZZCR
      INTEGER*2 I
     = ,CHARS,CHARE,CHARN(1) ! THE NAME OF THE PARAMETER
     = ,DEFLT ! THE DEFAULT-VALUE IF THE PARAMETER IS NOT WRITTEN
C
      IF (PARLAS .EQ. 0) GOTO 6
      DO 4 I = 1,PARLAS
        IF (ZZCR(CHARN,CHARS,CHARE
     =          ,PARM(1,I),1,PARME(I)) .NE.0)
     =  GOTO 4
C         PARAMETER WAS WRITTEN
          PARASK = PARVAL(I)
          GOTO 5
4     CONTINUE
C     PARAMETER WAS NOT WRITTEN:
6     CONTINUE
      PARASK = DEFLT
5     RETURN
      END
