      SUBROUTINE PREDEL(STATEA,STATEB)
C     DELETE 'STATEA' FROM THE SET OF PREDECESSORS OF 'STATEB'
C     GF 09.07.1980
C
      INCLUDE 'PARS.f'
      INCLUDE 'PRES.f'
      INCLUDE 'SETS.f'
      INCLUDE 'STAS.f'
      INTEGER*2 I
     = ,P1       ! -> ELEMENT BEFORE 'P2'
     = ,P2       ! -> CURRENT PREDECESSOR OF 'STATEB'
     = ,STATEA   ! DELETE THIS STATE
     = ,STATEB   ! DELETE FROM THE PREDECESSORS OF THIS STATE
C
      PRE(1) = STAPRE(STATEB)
      P1 = 1
      P2 = PRE(P1)!
6     IF(P2 .GE. PREHIB) GOTO 7
        IF (PRESTA(P2) .NE. STATEA) GOTO 8 ! RIGHT ELEMENT FOUND
          PRE(P1) = PRE(P2)
          PRE(P2) = FPRE!
          FPRE = P2
          GOTO 103
8       CONTINUE ! FOUND
        ! ELSE TRY NEXT ELEMENT
        P1 = P2
        P2 = PRE(P1)!
      GOTO 6
7     CONTINUE ! ALL PREDECESSORS
      ! 'STATEA' WAS NOT FOUND:
      CALL ASSERT(6,STATEA,STATEB)
103   CONTINUE
      STAPRE(STATEB) = PRE(1)
      CALL SEPUSH(STAMAR,STATEB,STAGAT,STAGAB)
      RETURN! PREDEL
      END
