C-------GF 28.08.1980------------------------- P R E S E M S
      INTEGER*2 FSEM,SEMHIB,PNOSEM
     = ,ACCO,ACIN,ACMA,ACTA  ! ACCUMULATOR
     = ,ATCO,ATIN,ATMA,SYAT  ! ATTRIBUTE
     = ,SOCO,REIN,UNCH,SOTA  ! SON, MEMBER
     = ,SYCO,SYIN,SYMA,SEPR  ! NEW SYMBOL
     = ,ACCU,ATTR,EOSY,EOS   ! MISCELLANEOUS
        INTEGER*2 SEMSYM(XXSEMH)
      INTEGER*2 SEM   (XXSEMH)
      COMMON /SEMS/
     =  FSEM      ! 1ST FREE 'SEM'-ENTRY
     = ,SEMHIB  ! HIGH BOUND OF 'SEM'
     = ,PNOSEM  ! -> DUMMY ACTION: UNCH, EOS
     = ,ACCO,ACIN,ACMA,ACTA  ! ACCUMULATOR
     = ,ATCO,ATIN,ATMA,SYAT  ! ATTRIBUTE
     = ,SOCO,REIN,UNCH,SOTA  ! SON, MEMBER
     = ,SYCO,SYIN,SYMA,SEPR  ! NEW SYMBOL
     = ,ACCU,ATTR,EOSY,EOS   ! MISCELLANEOUS
      EQUIVALENCE (PRE(1),SEM(1)),(PRESTA(1),SEMSYM(1))
