      INTEGER*2 FUNCTION PROLNG(PROD)
C     LENGTH OF THE RIGHT SIDE
C     (REPLACES AN ARRAY SET IN 'PROCHA')
C     GF 21.08.1980
C
      INCLUDE 'PARS.F'
      INCLUDE 'MEMS.F'
      INTEGER*2 FPRO,PROHIB
      INTEGER*2 PRO   (XXPROH),PROLEF(XXPROH)
      INTEGER*2 PROMON(XXPROH),PROSEM(XXPROH)
      COMMON /PROS/
     =  FPRO     ! 1ST FREE PRODUCTION
     = ,PROHIB   ! HIGH BOUND OF 'PROS'
     = ,PRO     ! -> NEXT PRODUCTION OF THE LEFT SIDE
     = ,PROLEF  ! SYMBOL ON THE LEFT SIDE
     = ,PROMON  ! -> FIRST MEMBER
     = ,PROSEM  ! -> SEMANTICS FOR THE PRODUCTION
      INTEGER*2 I
     = ,PROD
C
      I = PROMON(PROD)
1     IF(MEM(I) .EQ. EOP) GOTO 2
        I = I + 1
      GOTO 1
2     CONTINUE
      PROLNG = I - PROMON(PROD)
      RETURN
      END
