C-------GF 28.08.1980------------------------------------- P R O S
      INTEGER*2 FPRO,PROHIB
      INTEGER*2 PRO   (XXPROH),PROLNG,PROLEF(XXPROH)
      INTEGER*2 PROMON(XXPROH),PROSEM(XXPROH)
      COMMON /PROS/
     =  FPRO     ! 1ST FREE PRODUCTION
     = ,PROHIB   ! HIGH BOUND OF 'PROS'
     = ,PRO     ! -> NEXT PRODUCTION OF THE LEFT SIDE
     = ,PROLEF  ! SYMBOL ON THE LEFT SIDE
     = ,PROMON  ! -> FIRST MEMBER
     = ,PROSEM  ! -> SEMANTICS FOR THE PRODUCTION
