      SUBROUTINE PUTSYM (SYM)
C     PRINT THE EXTERNAL REPRESENTATION OF A SYMBOL
C     GF 11.07.1980
C     GF 27.12.1980: WITHOUT SYMBOL-NO.
C
      INCLUDE 'PARS.f'
      INCLUDE 'STRS.f'
      INCLUDE 'SYMS.f'
      INTEGER*2 PARASK
      INTEGER*2 SYM
C
      IF (PARASK('PUTSYN',1,6,0) .NE. 0)
     =  CALL ZZWI (SYM,0)
      CALL ZZWC('''',1,1,0)
      IF (SYM .LT. 2 .OR. SYM .GE. FSYM
     =    .OR. SYMLNK(1) .EQ. 0
     =  ) GOTO 1
        CALL ZZWC (STRNG,SYMPOS(SYM),SYMEND(SYM),0)
1     CONTINUE
      CALL ZZWC ('''',1,1,0)
      RETURN
      END
