      SUBROUTINE SCAINI
C     INITIALIZE THE SCANNER
C
      INCLUDE 'PARS.f'
      INCLUDE 'CODS.f'
      INCLUDE 'SYMS.f'
      INTEGER*2 I
C
      CALL CODINI(I) ! 110
      CALL LINIT ! 120,130
      CALL CODASS(' ',1,1,I) ! 140
      CALL CODASS('0123456789',1,10,I) ! 150
      CALL CODASS('ABCDEFGHIJKLMNOPQRSTUVWXYZ_',1,27,I) !160
      CALL CODASS('''',1,1,I) ! 170
C
      CALL HAINIT
      CALL SPEINI
CTES  PRINT *, 'SCAINI STARTED 4'
      CALL SPEINS('??',1,2,  ERRSYM)
      ! THIS SYMBOL IS RETURNED FOR ILLEGAL COMBINATIONS OF 110IALS
CTES  PRINT *, 'SCAINI STARTED 5'
      CALL SPEINS('/*',1,2,SCOBEG)
      CALL SPEINS('*/',1,2,SCOEND)
C
      CALL CODGET ! (SC)
CTES  PRINT *, 'SCAINI FINISHED:', SCOEND
      RETURN ! SCAINI
      END
