      SUBROUTINE SCANS (ANCH)
C     SCAN A SEQUENCE
C     GF 16.07.1980
C     GF 20.07.1980: 'PROHIB' -> 'TRAHIB' FOR NEW ENTITIES
C
C     DUMMY VERSION FOR THE READING OF GRAMMARS
C     CALLS 'SCAN' ONLY ONCE PER CALL
C
      INCLUDE 'PARS.F'
      INCLUDE 'PROS.F'
      INCLUDE 'STAS.F'
      INCLUDE 'STAT1.F'
      INCLUDE 'SYMS.F'
      INCLUDE 'TRAS.F'
      INTEGER*2 I
     = ,ACT     ! -> A NEW 'TRA'-ELEMENT
     = ,ANCH    ! ANCHOR FOR THE INPUT-STRING (RING)
     = ,ENTITY  ! RESULT OF 'SCAN'
     = ,SYMBOL  ! RESULT OF 'SCAN'
     = ,TEMP    ! FOR EXCHANGING IN *TRAPEN
      INCLUDE 'ENDS.F'
C
      CALL SCANR (  SYMBOL,ENTITY)
      IF (SYMBOL .GT. TSTRI) GOTO 1
C       HERE IT IS AN IDENTIFIER, NUMBER, STRING OR 'EOF'
        IF (SYMBOL .NE. TIDEN .OR. ENTITY .GT. GRAMAX
     =  ) GOTO 3
C         GRAMMAR-KEYWORD
          SYMBOL = TKEYW
3       CONTINUE
      GOTO 2
1     CONTINUE
        ENTITY = SYMBOL
        SYMBOL = TKEYW
2     CONTINUE
      CALL TRAPIM (ANCH,SYMBOL,ENTITY)
      ANCH = TRA(ANCH) ! -> 'TGOTO' AGAIN
      RETURN ! SCANS
      END
