      SUBROUTINE SEMARI (A2,OP)
C     PERFORM AN ARITHMETIC OPERATION ON 2 'TRA'-ELEMENTS
C     GF 21.07.1980
C     GF 08.11.1980: WITH #47 - FORCE A VALUE
C     GF 28.12.1980: THE OPERANDS MAY BE NON-NUMERIC
C
C     'SEMARI' DOES 'OP' AS POSTFIX-OPERATOR ON THE ELEMENT
C     'A1' BEFORE 'A2' AND 'A2', THE RESULT IS STORED IN 'A1',
C     AND 'A2' IS DELETED.
C
C     THE OPERANDS SHOULD BE NUMBER ENTITIES, OR 'TRAENT' MAY
C     CONTAIN THE VALUE DIRECTLY (IF 'TRAENT < 0'). THE
C     RESULT IS ALWAYS STORED IN THE LATTER WAY.
C
C     SINCE "NEGATIVE" MEANS "IMMEDIATE", ONLY NATURAL NUMBERS
C     MAY BE HANDLED, AND FOR 'OP = 2' THE RESULT IS ALSO ASSUMED
C     TO BE NONNEGATIVE !!
C
C     IF THE OPERANDS ARE NON-NUMERICAL, THE OPERATION-SYMBOL ('+','-',
C     '*' OR '/') IS INSERTED BETWEEN THE TWO OPERANDS, AND 'A2' IS
C     LEFT UNCHANGED.
C
      INCLUDE 'PARS.F'
      INCLUDE 'SYMS.F'
      INCLUDE 'TRAS.F'
      INTEGER*2 I
     = ,A1      ! -> 1ST OPERAND (= RESULT)
     = ,A2      ! -> 2ND OPERAND (IS FREED)
     = ,ACT     ! -> ELEMENT TO BE DELETED
     = ,N1      ! NUMERICAL VALUE OF 'A1'
     = ,N2      ! ... OF 'A2'
     = ,OP      ! = 1: ADD, 2: SUB, 3: MUL, 4: DIV
     = ,OPSYM   ! OPERATION-SYMBOL
     = ,POSSIB  ! = 1 (0) IF NUMERICAL EVALUATION (NOT) POSSIBLE
     = ,TEMP    ! A TEMPORARY FOR EXCHANGING
C
      POSSIB = 1 ! ASSUME: POSSIBLE
      A1 = TRA(A2)
1     IF (TRA(A1) .EQ. A2) GOTO 2
        A1 = TRA(A1)
      GOTO 1
2     CONTINUE
      IF (A1 .NE. A2) GOTO 3
        CALL ASSERT (135,OP,0)
C         ONLY ONE OPERAND FOR OPERATION @
        N1 = 0
        GOTO 100 ! SECOND
3     CONTINUE
      IF (TRASYM(A1) .NE. -TNUMB) GOTO 61
        POSSIB = 0
C       CALL ASSERT(136,-TRAENT(A1),0)
C         ARITHMETIC ON @ NOT POSSIBLE
      GOTO 62
61    CONTINUE
        N1 = TRAENT(A1)
        IF (N1 .GT. 0) GOTO 63
          N1 = - N1
        GOTO 64
63      CONTINUE
          CALL SYMNUM(N1,N1)
64      CONTINUE
62    CONTINUE
C
100   CONTINUE ! SECOND:
      IF (TRASYM(A2) .NE. -TNUMB) GOTO 71
        POSSIB = 0
C       CALL ASSERT(137,-TRAENT(A2),TRASYM(A2))
C         ARITHMETIC ON @ NOT POSSIBLE
      GOTO 72
71    CONTINUE
        N2 = TRAENT(A2)
        IF (N2 .GT. 0) GOTO 73
          N2 = - N2
        GOTO 74
73      CONTINUE
          CALL SYMNUM(N2,N2)
74      CONTINUE
72    CONTINUE
C
      IF (POSSIB .EQ. 1) GOTO 79
        GOTO (91,92,93,94,90,90,90),OP
79    CONTINUE
      GOTO (81,82,83,84,80,80,87),OP
C            +  -  *  /        =
80    CONTINUE
        CALL ASSERT (63,OP,0)
C         INVALID OPERATION @
          RETURN
81    CONTINUE
        N1 = N1 + N2
          GOTO 89
82    CONTINUE
        N1 = N1 - N2
          GOTO 89
83    CONTINUE
        N1 = N1 * N2
          GOTO 89
84    CONTINUE
        N1 = N1 / N2
          GOTO 89
87    CONTINUE
        IF (N1 .EQ. N2) GOTO 89
          CALL ASSERT (64,N1,N2)
C           '*@' NOT ALLOWED HERE, REPLACED BY '*@'
          N1 = N2
          GOTO 89
89    CONTINUE
C
      TRA(A1) = TRA(A2) ! -> 1ST
      TRASYM(A1) = TNUMB
      TRAENT(A1) = - N1
      TRA(A2) = A2
      CALL TRAPEN (FTRA,A2)
      A2 = A1
      RETURN
C
90    CONTINUE
        CALL ASSERT (63,OP,0)
C         INVALID OPERATION @
          RETURN
91    CONTINUE
        OPSYM = PLUS
          GOTO 99
92    CONTINUE
        OPSYM = MINUS
          GOTO 99
93    CONTINUE
        OPSYM = TIMES
          GOTO 99
94    CONTINUE
        OPSYM = DIVIDE
          GOTO 99
99    CONTINUE
      TRA(A1) = TRA(A2) ! LET 'A1' -> A RING
      CALL TRAPIM (A1,TKEYW,OPSYM)
      TRA(A1) = A2
      RETURN
      END
