C-------GF 28.08.1980--------------------------------- S E M S
C     2005-03-29: demingle PRESEMS
      INTEGER*2 FSEM,SEMHIB,PNOSEM
     = ,ACCO,ACIN,ACMA,ACTA  ! ACCUMULATOR
     = ,ATCO,ATIN,ATMA,SYAT  ! ATTRIBUTE
     = ,SOCO,REIN,UNCH,SOTA  ! SON, MEMBER
     = ,SYCO,SYIN,SYMA,SEPR  ! NEW SYMBOL
     = ,ACCU,ATTR,EOSY,EOS   ! MISCELLANEOUS
      INTEGER*2 SEMSYM(XXSEMH)
      INTEGER*2 SEM   (XXSEMH)
      COMMON /SEMS/
     =  FSEM      ! 1ST FREE 'SEM'-ENTRY
     = ,SEMHIB  ! HIGH BOUND OF 'SEM'
     = ,PNOSEM  ! -> DUMMY ACTION: UNCH, EOS
     = ,ACCO,ACIN,ACMA,ACTA  ! ACCUMULATOR
     = ,ATCO,ATIN,ATMA,SYAT  ! ATTRIBUTE
     = ,SOCO,REIN,UNCH,SOTA  ! SON, MEMBER
     = ,SYCO,SYIN,SYMA,SEPR  ! NEW SYMBOL
     = ,ACCU,ATTR,EOSY,EOS   ! MISCELLANEOUS
     = ,SEM     ! CONTAINS THE CODES 'ACCO...EOS'
     = ,SEMSYM  ! ADDITIONAL INFORMATION, MOSTLY A SYMBOL
