      SUBROUTINE SETINF (CHARN,CHARS,CHARE,XHEAD,XTAIL)
C     INFORM ABOUT A SINGLE SET/LIST/QUEUE
C     2005-05-06: XML OUTPUT
C
      INCLUDE 'PARS.F'
      INCLUDE 'SETS.F'
      INTEGER*2 XHEAD,XTAIL,CHARS,CHARE,CHARN(1)
      EXTERNAL OUTSET
C
      CALL ZZWC('  <set name="', 1, 13, 0) 
      CALL ZZWC(CHARN,CHARS,CHARE,0)
      CALL ZZWC('" head="', 1, 8, 0)
      CALL ZZWI(XHEAD,4)
      CALL ZZWC('" tail="', 1, 8, 0)
      CALL ZZWI(XTAIL,4)
      CALL ZZWC('>', 1, 1, 0)
      OUTSC = 0
      CALL LITRAC(SET,XHEAD,XTAIL,OUTSET,1)
      CALL ZZWC('  </set>', 1, 8, 0)
      CALL ZZWS (0)
      RETURN ! SETINF
      END
