C-------GF 28.08.1980----------------------------------- S E T S
C     2005-03-29: demingle MEMSETS
      INTEGER*2 FSET,SETHIB 
      INTEGER*2 SET   (XXSETH),SETELE(XXSETH)
     = ,EMITSH,EMITST,EMITSB   ! STA: FOR EMITT, SOURCE
     = ,EMITTH,EMITTT,EMITTB   ! STA: FOR EMITT, TARGET
     = ,LAGARH,LAGART,LAGARB   ! STA: FOR LAGAR
     = ,LAGETH,LAGETT,LAGETB   ! STA: FOR LAGET
     = ,LAPUTH,LAPUTT,LAPUTB   ! STA: FOR LAPUT
     = ,PRODEH,PRODET,PRODEB   ! PRO: FOR PRODEL
     = ,SPLITH,SPLITT,SPLITB   ! STA: FOR SPLIT
     = ,STACLH,STACLT,STACLB   ! SYM: FOR STACLO
     = ,STAGAH,STAGAT,STAGAB   ! STA: FOR STAGAR, ILL STATES
     = ,STAGBH,STAGBT,STAGBB   ! STA: FOR STAGAR, SURVIVING STATES
     = ,STAOPH,STAOPT,STAOPB   ! SYM: FOR STAOPN
     = ,STASUH,STASUT,STASUB   ! STA: FOR STASUC
     = ,SYMINH,SYMINT,SYMINB   ! SYM: FOR SYMINS
     = ,TREOUH,TREOUT,TREOUB   ! STA: FOR TREE-OUTPUT CHECK
     = ,GRASYH,GRASYT,GRASYB   ! SYM: SYMBOL IS IN GRAMMAR
     = ,OUTSC ! COUNTER FOR DUMP WITH 'LITRAC'
     = ,POT2     ! A POWER OF 2 TO SET A BIT
      COMMON /SETS/
     =  FSET
     = ,SETHIB
     = ,EMITSH,EMITST,EMITSB   ! STA: FOR EMITT, SOURCE
     = ,EMITTH,EMITTT,EMITTB   ! STA: FOR EMITT, TARGET
     = ,LAGARH,LAGART,LAGARB   ! STA: FOR LAGAR
     = ,LAGETH,LAGETT,LAGETB   ! STA: FOR LAGET
     = ,LAPUTH,LAPUTT,LAPUTB   ! STA: FOR LAPUT
     = ,PRODEH,PRODET,PRODEB   ! PRO: FOR PRODEL
     = ,SPLITH,SPLITT,SPLITB   ! STA: FOR SPLIT
     = ,STACLH,STACLT,STACLB   ! SYM: FOR STACLO
     = ,STAGAH,STAGAT,STAGAB   ! STA: FOR STAGAR, ILL STATES
     = ,STAGBH,STAGBT,STAGBB   ! STA: FOR STAGAR, SURVIVING STATES
     = ,STAOPH,STAOPT,STAOPB   ! SYM: FOR STAOPN
     = ,STASUH,STASUT,STASUB   ! STA: FOR STASUC
     = ,SYMINH,SYMINT,SYMINB   ! SYM: FOR SYMINS
     = ,TREOUH,TREOUT,TREOUB   ! STA: FOR TREE-OUTPUT CHECK
     = ,GRASYH,GRASYT,GRASYB   ! SYM: SYMBOL IS IN GRAMMAR
      COMMON /SETS/
     =  SET    ! -> NEXT ELEMENT
     = ,SETELE
     = ,OUTSC
     = ,POT2     ! A POWER OF 2 TO SET A BIT
