C-----GF 08.11.1980--------------------------------------------- S P A S
C     STATES WHICH ARE POSSIBLY AVAILABLE
      INTEGER*2 SPAHD,SPATL,SPAHIB,SPATES
      INTEGER*2 SPA(XXSPAH)
      INTEGER*2 SPASTA(XXSPAH),SPAIHD(XXSPAH),SPAITL(XXSPAH)
      COMMON /SPAS/
     =  SPAHD   ! -> 1ST FREE ELEMENT IN 'SPA'-RING
     = ,SPATL   ! -> LAST ELEMENT OCCUPIED
     = ,SPAHIB  ! HIGH BOUND OF 'SPAS'
     = ,SPA     ! -> NEXT ELEMENT IN RING
     = ,SPASTA  ! NUMBER OF THE STATE WHICH IS AVAILABLE
     = ,SPAIHD  ! -> 1ST 'ITE'-ELEMENT OF 'STATE'
     = ,SPAITL  ! -> LAST ...
      EQUIVALENCE (SPATES,PARVAL(XXPARH))
