      SUBROUTINE SPEINI
C     INITIALIZE THE ACCESS TO SPECIAL CHARACTERS
C
      INCLUDE 'PARS.F'
      INCLUDE 'SPES.F'
      INCLUDE 'STRS.F'
      INCLUDE 'SYMS.F'
      INTEGER*2 I
C
      SYMPOS(SYMHIB - 1) = STRHIB
CEND  SYMEND(SYMHIB - 1) = STRHIB - 1
      SYMPOS(SYMHIB) = STRHIB + 1
CEND  SYMEND(SYMHIB) = STRHIB + 1
      DO 11 I=1,8
        CALL ZZIC (127,HIGH8,I)
11    CONTINUE
      CALL ZZIC (127,STRNG,STRHIB) ! A MAXIMAL ELEMENT
      SPEH = FSYM
      FSYM = FSYM + 1!
      SYMLNK(SPEH) = SYMHIB - 1
      SYMPOS(SPEH) = FSTR
CEND  SYMEND(SPEH) = FSTR
      SYMPOS(FSYM) = FSTR + 1
      CALL ZZIC (0,STRNG,FSTR) ! A MINIMAL ELEMENT
      FSTR = FSTR + 1
      RETURN ! SPEINI
      END
