      SUBROUTINE STACLO(STATE)
C     ADD THE CLOSURE OF A SET OF SYMBOLS TO A STATE
C     GF 09.07.1980
C
      INCLUDE 'PARS.f'
      INCLUDE 'PROS.f'
      INCLUDE 'SETS.f'
      INCLUDE 'SYMS.f'
      INTEGER*2 I
     = ,ELEM     ! -> EVERY ELEMENT IN THE SET
     = ,ITEMEX   ! FOR CALL 'ITEINS', NOT USED
     = ,PROD     ! ALL PRODUCTIONS OF 'SYMBOL'
     = ,STATE    ! ADD,THIS STATE
     = ,SYMBOL   ! THE SYMBOL,BE CLOSED
     = ,SYMEX    ! .LE.0 IF (A SYMBOL WAS NOT YET IN 'STATE'
C
      ELEM = STACLH
21    IF(ELEM .EQ. STACLT) GOTO 22
        SYMBOL = SETELE(ELEM)
        PROD = SYMPRO(SYMBOL)
23      IF(PROD .GE. PROHIB) GOTO 24
          CALL ITEINS(STATE,PROMON(PROD),SYMEX,ITEMEX)
          IF (SYMEX .GT. 1)
     =      CALL SEPUSH(SYMMAR,SYMEX,STACLT,STACLB)
          PROD = PRO(PROD)
        GOTO 23
24      CONTINUE ! ALL PRODUCTIONS
        ELEM = SET(ELEM)
      GOTO 21
22    CONTINUE ! ALL SYMBOLS IN 'STACLO'-SET
      CALL SETFRE(SYMMAR,STACLH,STACLT,STACLB)
      RETURN! STACLO
      END
