C-------GF 28.08.1980--------------------------------- S T A S
      INTEGER*2 FSTA,STAHIB,FNUM,STATE2
      INTEGER*2 STAITE(XXSTAH),STAPRE(XXSTAH),STARST(XXSTAH)
      INTEGER*2 STASYM(XXSTAH)
      INTEGER*2 STAMAR(XXSTAH)
      COMMON /STAS/
     =  FSTA     ! 1ST FREE STATE
     = ,STAHIB   ! HIGH BOUND OF 'STAS'
     = ,FNUM     ! 1ST FREE TIME_STAMP FOR 'STASEA'
     = ,STATE2   ! THE PARSER STARTS IN THIS STATE
     = ,STAITE  ! -> FIRST ITEM, -> NEXT FREE STATE
      COMMON /STAS/
     =  STAPRE  ! -> FIRST PREDECESSOR
     = ,STARST  ! -> NEXT STATE WITH SAME REACHING SYMBOL
     = ,STASYM  ! THE STATE WAS REACHED BY THIS SYMBOL
     = ,STAMAR  ! VARIOUS MARKING BITS
