C-------GF 01.08.1980--------------------------------- S T A T 1
C       STATICS FOR 'SEMANT'
        INTEGER*2 DESL,DESU,INGRAM,BULEFT,MEMPOS,BUMON,BUPROD,REIPOS
      INTEGER*2 NEWNUM
        COMMON /STAT1/
     =  BULEFT    ! LEFT SIDE OF 'BUPROD'
     = ,BUMON     ! -> MEMBER NUMBER ONE OF THE PRODUCTION TO BE BUILT
     = ,BUPROD    ! THE NEW PRODUCTION BUILT BY 'PROCHA'
     = ,DESL    ! DESTINATION, LOWER ELEMENT
     = ,DESU    ! ... HIGH ELEMENT. DESU = DESL +0/+1
     = ,INGRAM  ! = 0 (1) IFF 'SOURCE_TEXT' ('GRAMMAR') IS PARSED
     = ,MEMPOS      ! TO DETERMINE 'REIPOS'
     = ,NEWNUM  ! FOR THE GENERATION OF FORTRAN STATEMENT-NUMBERS
     = ,REIPOS  ! THE POSITION OF THE '@'
