C-------GF 08.09.1980--------------------------------------- S T K S
      INTEGER*2 FSTK,STKHIB,STKSTA(XXSTKH),STKTRA(XXSTKH)
      INTEGER*2 STKSYM(XXSTKH)
      COMMON / STKS/ ! PUSHDOWN-STORE OF THE PARSER
     =  FSTK     ! 1ST FREE 'STK' FOR THE STACK OF STATES
     = ,STKHIB   ! HIGH BOUND OF 'STKS'
     = ,STKSTA  ! STACK FOR STATES, HEAP OF STACKS FOR ACCUMULATORS
     = ,STKTRA  ! -> 1ST ELEMENT OF A NONT./ACCU IN 'TRE'
     = ,STKSYM  ! THE SYMBOL WHICH WAS SHIFTED
