      INTEGER*2 FUNCTION SYMEND(SYMBOL)
C     -> LAST CHARACTER OF A SYMBOL
C     REPLACES THE CORRESPONDING ARRAY (SET BY 'HAMAP','SPEINS')
C     GF 20.08.1980
C
      INCLUDE 'PARS.f'
      INTEGER*2 FSYM,SYMHIB
      INTEGER*2 SYMLOB,SPEH,ERRSYM,SCOBEG,SCOEND
      INTEGER*2 EOFILE,IDENT,NUMBER,STRIN
      INTEGER*2 EOSTMT,AXIOM,GRAMAX
      INTEGER*2 SYMPRO(XXSYMH),SYMMAR(XXSYMH),SYMRST(XXSYMH)
      INTEGER*2 SYMPOS(XXSYMH),SYMLNK(XXSYMH)
      COMMON /SYMS/
     =  FSYM    ! 1ST FREE ENTRY
     = ,SYMHIB  ! MAXIMUM OF POSSIBLE SYMBOLS
     = ,SYMLOB  ! LOW BOUND OF 'SYMS', = 1
     = ,SPEH    ! -> LIST OF COMBINATIONS OF SPECIAL CHARACTERS
     = ,ERRSYM  ! CODE FOR INVALID CHARACTERS
     = ,SCOBEG  ! BEGIN OF COMMENT
     = ,SCOEND  ! END   OF COMMENT, = 5
     = ,EOFILE  ! THE FOLLOWING 4 SYMBOLS DO  NOT  STAND FOR THEMSELF
     = ,IDENT
     = ,NUMBER
     = ,STRIN
     = ,EOSTMT  ! END-OF-STATEMENT SYMBOL
     = ,AXIOM   ! THE START-SYMBOL OF ALL GRAMMARS
     = ,GRAMAX  ! THE LAST SYMBOL BELONGING TO THE GRAMMAR
      COMMON /SYMS/
     =  SYMPRO  ! -> 1ST PRODUCTION IF NONTERMINAL
     = ,SYMPOS  ! -> 1ST CHARACTER IN 'STRNG'
     = ,SYMLNK  ! -> NEXT SYMBOL WITH SAME HASH-CODE
CEQU  EQUIVALENCE (SYMMAR(1),SYMLNK(1))
CEQU  EQUIVALENCE (SYMRST(1),SYMPOS(1))
      INTEGER*2 SYMBOL
C
      SYMEND = SYMPOS(SYMBOL + 1) - 1
      RETURN
      END
