C-------GF 28.12.1980------------------------------- S Y M S
      INTEGER*2 FSYM,SYMHIB
      INTEGER*2 SYMLOB,SPEH,ERRSYM,SCOBEG,SCOEND
      INTEGER*2 EOFILE,IDENT,NUMBER,STRIN
      INTEGER*2 EOSTMT,AXIOM,GRAMAX
      INTEGER*2 SYMPRO(XXSYMH),SYMMAR(XXSYMH),SYMRST(XXSYMH)
      INTEGER*2 SYMPOS(XXSYMH),SYMEND,SYMLNK(XXSYMH)
      INTEGER*2 ARROW,BAR,EQUALS,MINUS,PERIOD
      INTEGER*2 BUS,SUB,NUMSIG,SEMI,OPENP,CLOSP
      INTEGER*2 PLUS,TIMES,DIVIDE
      COMMON /SYMS/
     =  FSYM    ! 1ST FREE ENTRY
     = ,SYMHIB  ! MAXIMUM OF POSSIBLE SYMBOLS
     = ,SYMLOB  ! LOW BOUND OF 'SYMS', = 1
     = ,SPEH    ! -> LIST OF COMBINATIONS OF SPECIAL CHARACTERS
     = ,ERRSYM  ! CODE FOR INVALID CHARACTERS
     = ,SCOBEG  ! BEGIN OF COMMENT
     = ,SCOEND  ! END   OF COMMENT, = 5
     = ,EOFILE  ! THE FOLLOWING 4 SYMBOLS DO  NOT  STAND FOR THEMSELF
     = ,IDENT
     = ,NUMBER
     = ,STRIN
     = ,EOSTMT  ! END-OF-STATEMENT SYMBOL
     = ,AXIOM   ! THE START-SYMBOL OF ALL GRAMMARS
     = ,GRAMAX  ! THE LAST SYMBOL BELONGING TO THE GRAMMAR
      COMMON /SYMS/
     =  SYMPRO  ! -> 1ST PRODUCTION IF NONTERMINAL
     = ,SYMPOS  ! -> 1ST CHARACTER IN 'STRNG'
     = ,SYMLNK  ! -> NEXT SYMBOL WITH SAME HASH-CODE
     = ,SYMMAR  ! MARKING AND -> 'TRAS'
      COMMON /SYMS/
     =  ARROW  ! =>
     = ,BAR    ! |
     = ,EQUALS ! =
     = ,MINUS  ! -
     = ,PERIOD ! .
     = ,BUS    ! ]
     = ,SUB    ! [
     = ,NUMSIG ! #
     = ,SEMI   ! ;
      COMMON /SYMS/
     =  OPENP  ! (
     = ,CLOSP  ! )
     = ,PLUS   ! +
     = ,TIMES  ! *   ('MINUS' SEE ABOVE)
     = ,DIVIDE ! /
CEQU  EQUIVALENCE (SYMRST(1),SYMPOS(1))
