      INTEGER*2 FTAR,TARHIB,TARBUF(XXTARH)
      COMMON /TARS/
     =  FTAR   ! 1ST FREE TARNT POSITION
     =, TARHIB ! LAST AVAILABLE TARNT POSITION
     =, TARBUF ! BUFFER WHICH COLLECTS STREAM TARNT-OUT
