      SUBROUTINE TRADO (ANCH,APPLY)
C     DO SOMETHING WITH ALL ELEMENTS OF RING 'ANCH'
C     GF 21.07.1980
C
C     FOR THE ELEMENTS 'ACT' = 'TRA(ACT)' ... 'ANCH':
C
C       CALL APPLY(ACT)
C
C     IN ADDITION, INFINITE LOOPS ARE AVOIDED.
C
      INCLUDE 'PARS.f'
      INCLUDE 'TRAS.f'
      INTEGER*2 LOOPCH
     = ,ACT     ! -> CURRENT ELEMENT
     = ,ANCH     ! -> ELEMENT IN THE RING
      INCLUDE 'ENDS.f'
C
      IF (ANCH .EQ. TRAHIB) RETURN
      LOOPCH = 0
      ACT = TRA(ANCH) ! -> 1ST
      CALL APPLY (ACT)
1     IF(ACT .EQ. ANCH) GOTO 2
        LOOPCH = LOOPCH + 1
        IF (LOOPCH .LE. TRAHIB) GOTO 3
          CALL ASSERT (138,ACT,FTRA)
          CALL TRADUM (0) ! DUMP THE ENTIRE 'TRA'-STRUCTURE
          RETURN
3       CONTINUE
        ACT = TRA(ACT)
        CALL APPLY (ACT)
      GOTO 1
2     CONTINUE
      RETURN
      END
