      SUBROUTINE TRAOUT (ASEM,LEFT,TRALEF)
C     TEST PRINT-OUT FOR SIGNIFICANT ACTIONS IN 'TRAFOR'
C     GF 24.07.1980
C
      INTEGER*2 I
     = ,ASEM    ! -> SEMANTIC ACTION FOR THE DESTINATION
     = ,LEFT    ! THE SYMBOL WHICH IS ASSIGNED TO
     = ,TRALEF  ! THE RING WHICH IS ASSIGNED TO 'LEFT'
      EXTERNAL TRAO1
C
      I = ASEM
      CALL OUTSEM (I)
      CALL PUTSYM (LEFT)
      CALL ZZWC ('->',1,2,0)
      CALL TRADO (TRALEF,TRAO1) ! OUTPUT EVERY SINGLE ELEMENT
      CALL ZZWS (0)
      RETURN
      END
