      SUBROUTINE TRAPEN (TARGET,SOURCE)
C     CONCATENATE RING 'TARGET' WITH RING 'SOURCE'
C     GF 24.07.1980
C
      INCLUDE 'PARS.f'
      INCLUDE 'TRAS.f'
      INCLUDE 'ENDS.f'
      INTEGER*2 I
     = ,SOURCE  ! THIS RING IS APPENDED
     = ,TARGET  ! APPEND AT THE RIGHT OF THIS RING (RESULT)
C
      IF (SOURCE .EQ. TRAHIB) GOTO 1
        IF (TARGET .EQ. TRAHIB) GOTO 2
          I = TRA(TARGET) ! INTERCHANGE 2 POINTERS
          TRA(TARGET) = TRA(SOURCE)
          TRA(SOURCE) = I
2       CONTINUE ! TARGET NOT EMPTY
        TARGET = SOURCE ! NEW RESULT
1     CONTINUE ! SOURCE NOT EMPTY
      RETURN
      END
