      SUBROUTINE TRATTR (ASEM,  SYMB,INC,A1,A2)
C     ACCESS TO AN ATTRIBUTE
C     GF 16.07.1980
C     GF 24.07.1980: SIMPLER VERSION
C
C     1 <= A1 < A2 <= TRAHIB
C     A1 -> A2
C     A2 -> INC: FOUND, OR A2 = TRAHIB: NOT FOUND
C     INSERT BETWEEN 'A1,A2', RESULTING ANCHOR IS IN 'TRA(1)'
C     ASEM += 1
C
      INCLUDE 'PARS.f'
      INCLUDE 'SEMS.f'
      INCLUDE 'STKS.f'
      INCLUDE 'SYMS.f'
      INCLUDE 'TRAS.f'
      INTEGER*2 I
     = ,A1,A2   ! 2 SUCCEEDING POINTERS TO THE LIST OF ATTRIBUTES
     = ,ASEM    ! -> ATTRIBUTE-ACTION IN 'SEM'
     = ,INC     ! THE INCARNATION OF 'SYMB'
     = ,SYMB    ! THE NAME OF THE ATTRIBUTE
      INCLUDE 'ENDS.f'
C
      I = FSTK + SEMSYM(ASEM) - 1 ! ACCESS TO THE SON
      ASEM = ASEM + 1
      INC  = SEMSYM(ASEM)
      A1 = 1
      A2 = STKTRA(I)
      IF (A2 .NE. TRAHIB) GOTO 3
        CALL ASSERT (133,SEMSYM(ASEM-1),-INC)
C         EMPTY SON @, ATTRIBUTE @ IS UNDEFINED
        SYMB = ERRSYM
        TRA(A1) = A2
        GOTO 99
3     CONTINUE
      A2 = TRA(A2) ! -> 1ST
      IF (TRASYM(A2) .GE. TIDEN .AND. TRASYM(A2) .LE. TSTRI) GOTO 4
        CALL ASSERT (134,-TRASYM(A2),-INC)
C         @ IS NO ENTITY, ATTRIBUTE @ IS UNDEFINED
        A2 = TRAHIB
        SYMB = ERRSYM
        TRA(A1) = A2
        GOTO 99
4     CONTINUE
C
      SYMB = TRAENT(A2)
      A2 = SYMMAR(SYMB)
      IF (A2 .EQ. 0) A2 = TRAHIB
      TRA(A1) = A2
1     IF(TRASYM(A2) .EQ. INC .OR. A2 .EQ. TRAHIB) GOTO 2
        A1 = A2 ! LOOK AT NEXT IN THE LIST
        A2 = TRA(A1)
      GOTO 1
2     CONTINUE
99    RETURN ! TRATTR
      END
