      SUBROUTINE TREFRE (RECNO)
C     FREE A SLOT EXPLICITELY
C     GF 26.07.1980
C
      INCLUDE 'PARS.F'
      INCLUDE 'SLOS.F'
      INTEGER*2 I
     = ,RECNO     ! FREE THE SLOT WHICH CONTAINS THIS RECORD
      INCLUDE 'ENDS.F'
C
      DO 4 I = 1,SLOHIB
        IF (SLOFUL(I) .NE. RECNO) GOTO 4
          SLOFUL(I) = 0
          GOTO 98
4     CONTINUE
98    RETURN
      END
