      SUBROUTINE TREGET (REF,  COL,ROW)
C     GET A 'TRE'-RECORD FROM THE DIRECT-FILE
C     GF 26.07.1980
C
      INCLUDE 'PARS.f'
      INCLUDE 'SLOS.f'
      INCLUDE 'TRES.f'
      INTEGER*2 I
     = ,COL     ! THE RECORD IS READ IN THIS COLUMN
     = ,RECNO ! -> RECORD WHICH CONTAINS ELEMENT NO. 'REF'
     = ,REF   ! A 'TRE'-ELEMENT TO BE ACCESSED
     = ,ROW   ! -> 'TRE', ELEMENT WITH LOGICAL NUMBER 'REF'
      INCLUDE 'ENDS.f'
C
      RECNO = (REF - 1) / TREHIB + 1
      ROW = REF - (RECNO - 1) * TREHIB
      COL = 0
      DO 1 I = 1,SLOHIB ! LOOK FOR 'RECNO' RESP. FREE SLOT
        IF (SLOFUL(I) .NE. RECNO) GOTO 2
          COL = I
          GOTO 99
2       CONTINUE
        IF (SLOFUL(I) .EQ. 0) COL = I
1     CONTINUE ! LOOK FOR 'RECNO'
C
      IF (COL .NE. 0) GOTO 3
        FSLO = MOD(FSLO,SLOHIB) + 1
        COL = FSLO
        TRECNO = SLOFUL(COL)
C       WRITE (UTRE'TRECNO) (SLOT(I,COL),I=1,TREHIB)
3     CONTINUE
      SLOFUL(COL) = RECNO
      TRECNO = RECNO
C     READ (UTRE'TRECNO) (SLOT(I,COL),I=1,TREHIB)
99    CONTINUE
      RETURN
      END
