      SUBROUTINE TREPUT (ACT)
C     PUT A COMBINED SYMBOL TO THE EXTERNAL TREE
C     GF 16.07.1980  DUMMY VERSION
C
      INCLUDE 'PARS.f'
      INCLUDE 'TRAS.f'
      INCLUDE 'TRES.f'
      INTEGER*2 PARASK
      INTEGER*2 I
     = ,ACT     ! WRITE THIS 'TRA'-ELEMENT TO THE EXTERNAL TREE
      INCLUDE 'ENDS.f'
C
      IF (PARASK('TREPUT',1,6,1) .EQ. 0) RETURN
      IF (TRASYM(ACT) .EQ. TVOID) RETURN
      I = MOD(FTRE-1,TREHIB) + 1 ! E.G. TREHIB+1 -> 1
      TRE(I) = TRASYM(ACT)
      TRE(I+1) = TRAENT(ACT)
      FTRE = FTRE + 2
      IF (I+2 .LT. TREHIB) GOTO 1
C       WRITE (UTRE'TRECNO) TRE ! TRECNO += 1
        FTRE = (TRECNO-1) * TREHIB + 1
1     CONTINUE
      RETURN
      END
