C-----GF 24.07.1980-------------------------------------------- T R E S
      INTEGER*2 FTRE,TRECNO,TREHIB,TRE(XXTREH)
      COMMON /TRES/
     =  FTRE    ! 1ST FREE ELEMENT IN 'TRE'
     = ,TRECNO  ! NUMBER OF THE NEXT RECORD TO BE WRITTEN
     = ,TREHIB  ! HIGH BOUND OF 'TRE'
     = ,TRE     ! BUFFER FOR THE CONTENTS OF COMBINED SYMBOLS
