      INTEGER*2 FUNCTION ZZINDX (CHARN,CHARS,CHARE,SEARCH)
C     -> PL/1, 2ND PARAMETER ONLY 1 CHARACTER
C     GF 21.07.1980
C
      INTEGER*2 ZZCR
      INTEGER*2 CHARN(1),CHARS,CHARE ! CHARACTERS WITH START- AND END-POS.
      INTEGER*2 SEARCH ! LOOK FOR THIS CHARACTER
      INTEGER*2 I
C
      DO 1 I = CHARS,CHARE
        IF (ZZCR(CHARN,I,I,SEARCH,1,1) .NE. 0) GOTO 1
          ZZINDX = I
          GOTO 99
1     CONTINUE
C     'SEARCH' WAS NOT FOUND HERE
      ZZINDX = 0
99    CONTINUE
      RETURN
      END
