      SUBROUTINE ZZTC(CHARN,CHARS,CHARE,WIDTH)
C     WRITE CHARACTERS TO STREAM-OUTPUT
C
      INCLUDE 'PARS.F'
      INCLUDE 'TARS.F'
      INTEGER*2 CHARS,CHARE,CHARN(1),WIDTH
      INTEGER*2 LNG
C
      LNG = WIDTH
      IF (LNG .EQ. 0)
     =    LNG = CHARE - CHARS + 1
      CALL ZZTS(LNG)
      CALL ZZCC(CHARN,CHARS,CHARE,TARBUF,FTAR,FTAR + LNG)
      FTAR = FTAR + LNG
      RETURN
      END
