      SUBROUTINE ZZTI (INT,WIDTH)
C     2022-02-07: *DR=112
C     WRITE AN INTEGER TO STREAM OUTPUT
C
      IMPLICIT NONE
      INTEGER*2 IBHIB
      PARAMETER (IBHIB=10)
      INTEGER*2 I
     = ,INT      ! THE NUMBER TO BE ENCODED
     = ,WIDTH    ! WRITE SO MUCH CHARACTERS
     = ,LNG      ! TO DETERMINE THE WIDTH IF 'WIDTH=0'
     = ,IBPOS    ! IN IBUF
      CHARACTER*10 IBUF ! ENCODE IN THIS ARRAY
      
      WRITE (IBUF,70) INT
70    FORMAT (I10)
      IBPOS = VERIFY(IBUF, ' ')
      CALL ZZTC(IBUF,IBPOS,10,WIDTH)
      RETURN
      END
