      SUBROUTINE ZZTT (POS)
C     TABULATE TO POSITION 'POS' IN STREAM-OUTPUT
C     GF 16.07.1980
C
      INCLUDE 'PARS.f'
      INCLUDE 'TARS.f'
      INTEGER*2 POS
C
      IF (FTAR .LE. POS) GOTO 1
        CALL ZZTS(0)
1     CONTINUE
      IF (FTAR .EQ. POS) GOTO 2
        CALL ZZTX (POS - FTAR)
2     CONTINUE
      RETURN
      END
