      SUBROUTINE ZZWC(CHARN,CHARS,CHARE,WIDTH)
C     WRITE CHARACTERS TO STREAM-OUTPUT
C
      INCLUDE 'PARS.F'
      INCLUDE 'PRIS.F'
      INTEGER*2 CHARS,CHARE,CHARN(1),WIDTH
      INTEGER*2 LNG
C
      LNG = WIDTH
      IF (LNG .EQ. 0)
     =    LNG = CHARE - CHARS + 1
      CALL ZZWS(LNG)
      CALL ZZCC(CHARN,CHARS,CHARE,PRIBUF,FPRI,FPRI + LNG)
      FPRI = FPRI + LNG
      RETURN
      END
